// <auto-generated />
using System;
using Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Api.Reportes.AvisoSapPm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionCorta")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EquipoContinuaOperando")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaIncioAveria")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("HoraInicioAveria")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModoFalla")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModoFallaImg")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParteObjectoAfectada")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParteObjectoAfectadaImg")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SolucionadoPorBEC")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UbicacionTecnica")
                        .HasColumnType("TEXT");

                    b.Property<string>("UbicacionTecnicaImg")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AvisosSapPm");
                });

            modelBuilder.Entity("Api.Reportes.AvisoY2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CorregidoPorMantenimiento")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IdEvento")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroAvisoY2")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AvisosY2");
                });

            modelBuilder.Entity("Api.Reportes.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .HasColumnType("TEXT");

                    b.Property<string>("CerradoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Coordenadas")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Impacto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapaUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prioridad")
                        .HasColumnType("TEXT");

                    b.Property<string>("PuestoSeguridad")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEvento")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEventoImagen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Api.Reportes.Firma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaImagen")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Firmas");
                });
#pragma warning restore 612, 618
        }
    }
}
